# UNSUPERVISED LEARNING

# MARKET BASKET ANALYSIS USING ASSOCIATION RULES

analysis performed on customers in the market
how customers are purchasing the goods
so we can relate the probabilities of another realted items also
like purcahsing bread, possibilities of prchasing -> butter also

retailers uses sophisticated data techniques

most recently as barcode scanners, computerized inventory system, amd online shopping trends have built a wealth of transcatonal data
machine learning has been increasingly applied to learn the purchasing patterns

thsi practice is commonly known as market basket analysis due to the fact that it has been so frequently applied to supermarket data

ASSOCIATION RULES

building blocks of market basket analysis are the items that are sold so frequently
groups of one o more items are surrounded by brackets to indicate thet they form a set, or more specifically, an itemset that appears in the data
with some irregularity

{bread,peanut butter, jelly}

subsets of itemsets are denoted by relating one itemset one LHS of rule to another itemset on RHS
LHS is the condition need to met in order to trigger the rule
RHS is the expected result of that condition

{peanut butter, jelly} -> {bread}

association rules are unsupervised , there is no need for the algorithm to be trained
data does not need to be labeled one
program is simply unleashed

association rule mining ->
    A -> B
        support = freq(A,B) / N

        confidence = freq(A,B) / freq(A)

        Lift = support / support(A) * support(B)

T1    A    B   C
T2    A    C   D
T3    B    C   D
T4    A    D   E
T5    B    c   E

RULES=    supp.   conf.   lift
A -> D =  2/5     2/3    10/9 = 
C -> A =  2/5     2/4    5/6
A -> C =  2/5     2/3    5/6
B & C -> A = 1/5  1/3    5/9

support = 1/5
conf = 1 / 3
lift = 1/5 / (3/5 * 3/5) = 25*1 / 9*5 = 5/9

support should be minimum of 20% -> need to do percentage

Apriori Algorithm -> (not works with null values)

uses frequently itemset to generate association rules
based on the concept -> subset of frequent itemset must also be a frequent itemset
concession can also apply, so this priciple works here

frequent itemset -> whose support value is greater than a threshold value
single item support avlue should be higher than 20%(assuming it is given) or like (min. support count=2)

remove items having support value less than threshold value

then, time for association->

make combinations of all items after eliminating 
now find support for combintions as well and then find elimiantion

antecedents -> left side values
consequents - > right side values

for every subset S of I, that is:

S -> (I-S)

if(supp(I)/supp(S) >= min. conf value)

if lift is near 1 or <1 then we can go with that combination for itemset / strong association
if it is near to 0 then we don't need to go with that itemset

In [ ]:
handling null values in Apriori algorithm ->

In [1]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.16.3 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: joblib>=1.5.2 in f:\python_env\new_python_env\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in f:\python_env\new_python_env\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in f:\python_env\new_python_env\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in f:\python_env\new_python_env\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in f:\python_env\new_python_env\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.2.0 in f:\python_env\new_python_env\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 383.9 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 383.9 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 383.9 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 383.9 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 383.9 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 321.1 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 257.7 kB/s eta 0:00:02
   -------------------------------------- - 1.3/1.4 MB 215.8 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 218.1 kB/s  0:00:06
Installing collected packages: mlxtend
Successfully installed mlxtend-0.24.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

transactions = []

with open("groceries (1).csv","r") as f:
    for line in f:
        items = line.strip().split(",")
        transactions.append(items)

# OHE columns
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_array, columns = te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [5]:
# Apriori ->

freq_items = apriori(df, min_support = 0.02, use_colnames = True)
freq_items

      support                                         itemsets
0    0.033452                                       (UHT-milk)
1    0.052466                                           (beef)
2    0.033249                                        (berries)
3    0.026029                                      (beverages)
4    0.080529                                   (bottled beer)
..        ...                                              ...
117  0.032232                 (whole milk, whipped/sour cream)
118  0.020742                     (whipped/sour cream, yogurt)
119  0.056024                             (whole milk, yogurt)
120  0.023183  (whole milk, other vegetables, root vegetables)
121  0.022267           (whole milk, other vegetables, yogurt)

[122 rows x 2 columns]

In [7]:
# Association rules

rules = association_rules(freq_items, metric = 'confidence', min_threshold = 0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(beef),(whole milk),0.052466,0.255516,0.021251,0.405039,1.585180,1.0,0.007845,1.251315,0.389597,0.074113,0.200841,0.244103
1,(bottled beer),(whole milk),0.080529,0.255516,0.020437,0.253788,0.993237,1.0,-0.000139,0.997684,-0.007351,0.064755,-0.002321,0.166886
2,(bottled water),(other vegetables),0.110524,0.193493,0.024809,0.224471,1.160101,1.0,0.003424,1.039945,0.155154,0.088857,0.038411,0.176345
3,(bottled water),(rolls/buns),0.110524,0.183935,0.024199,0.218951,1.190373,1.0,0.003870,1.044832,0.179800,0.089541,0.042909,0.175258
4,(bottled water),(soda),0.110524,0.174377,0.028978,0.262190,1.503577,1.0,0.009705,1.119017,0.376535,0.113230,0.106359,0.214185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,"(other vegetables, root vegetables)",(whole milk),0.047382,0.255516,0.023183,0.489270,1.914833,1.0,0.011076,1.457687,0.501524,0.082879,0.313982,0.289999
69,(root vegetables),"(whole milk, other vegetables)",0.108998,0.074835,0.023183,0.212687,2.842082,1.0,0.015026,1.175091,0.727435,0.144304,0.149002,0.261235
70,"(whole milk, other vegetables)",(yogurt),0.074835,0.139502,0.022267,0.297554,2.132979,1.0,0.011828,1.225003,0.574138,0.115934,0.183676,0.228588
71,"(whole milk, yogurt)",(other vegetables),0.056024,0.193493,0.022267,0.397459,2.054131,1.0,0.011427,1.338511,0.543633,0.097987,0.252901,0.256270
72,"(other vegetables, yogurt)",(whole milk),0.043416,0.255516,0.022267,0.512881,2.007235,1.0,0.011174,1.528340,0.524577,0.080485,0.345695,0.300014

In [9]:
rules_simple = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
print(rules_simple.head())

       antecedents         consequents   support  confidence      lift
0           (beef)        (whole milk)  0.021251    0.405039  1.585180
1   (bottled beer)        (whole milk)  0.020437    0.253788  0.993237
2  (bottled water)  (other vegetables)  0.024809    0.224471  1.160101
3  (bottled water)        (rolls/buns)  0.024199    0.218951  1.190373
4  (bottled water)              (soda)  0.028978    0.262190  1.503577

In [10]:
# so from above the first rule is showing the strong association having highest lift as 1.58 and having prob. as 40%